version: 2.1

orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@3.2.2

jobs:
  tests:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn cover
      - codecov/upload:
          file: coverage/*.json

workflows:
  ci:
    jobs:
      - tests
