version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  setup:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn --version

workflows:
  ci:
    jobs:
      - setup
